### ISSUE TITLE
sqrt is not square

### ISSUE THREAD

**Issue by PierreGaudichon** [somebee/imba.io#4]
In the [doc for methods](https://github.com/somebee/imba.io/blob/master/docs/guides/language.md#methods), there is :

```
def sqrt num
    num * num
```

Which should be :

```
def square num
    num * num
```

EDIT : Same for blocks, just below.

**Comment by somebee** [comment]
Thanks :) Fixed now - will deploy with some other changes soon

**Comment by PierreGaudichon** [comment]
Fixed in 3 min, GG !
