### ISSUE TITLE
can't start server 

### ISSUE THREAD

**Issue by frh3ddy** [somebee/imba.io#9]
when I run gulp server i get this error
```javascript 
{ [Error: spawn imba ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn imba',
  path: 'imba',
  spawnargs: [ 'src/server.imba' ] }
```
and also I was getting an error that said scrimbla/src/core/highlighter module cannot be found,

**Comment by somebee** [comment]
I think this should be solved in the latest commit :)
